<?php

namespace AppBundle\Repository;

/**
 * Bestelopdracht_ArtikelenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bestelopdracht_ArtikelenRepository extends \Doctrine\ORM\EntityRepository
{
}
