<?php

namespace AppBundle\Repository;

/**
 * ReserveringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReserveringRepository extends \Doctrine\ORM\EntityRepository
{
}
