<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZmj7nky\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZmj7nky/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerZmj7nky.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerZmj7nky\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerZmj7nky\appProdProjectContainer(array(
    'container.build_hash' => 'Zmj7nky',
    'container.build_id' => '50e37f12',
    'container.build_time' => 1525856162,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZmj7nky');
