<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1vw6mh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1vw6mh/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerY1vw6mh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerY1vw6mh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerY1vw6mh\appProdProjectContainer(array(
    'container.build_hash' => 'Y1vw6mh',
    'container.build_id' => '0574e8f8',
    'container.build_time' => 1525700890,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1vw6mh');
