<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNdqmn6i\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNdqmn6i/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNdqmn6i.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNdqmn6i\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNdqmn6i\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ndqmn6i',
    'container.build_id' => 'daab393c',
    'container.build_time' => 1525854506,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNdqmn6i');
